### ISSUE TITLE
Address sanitizer fails

### ISSUE THREAD

**Issue by alex-ozdemir** [cocoa-official/CoCoALib#43]
Hi John and Anna,

Just so you know: CoCoALib currently does not work with address sanitization. An example:

```
$ git clone git@github.com:cocoa-official/CoCoALib.git
$ cd CoCoALib
$ git apply fix-gmp-config-test.txt # attached
$ ./configure --only-cocoalib --with-cxxflags="-fsanitize=address"
$ make -j $(nproc)
[ALL TESTS FAIL]
$ cd src/tests
$ ./test-empty
[FAILS WITH ASAN ERROR]
```

[fix-gmp-config-test.txt](https://github.com/user-attachments/files/20358557/fix-gmp-config-test.txt)

We discovered this because [somebody ran cvc5 with ASAN and it failed because of CoCoA](https://github.com/cvc5/cvc5/issues/11902).

I'm not sure whether you want to fix this, but I figured you would want to know. We would find a fix helpful but non-essential.

Cheers,
Alex

**Comment by JohnAAbbott** [comment]
Thanks for bringing this to our attention.  We will investigate next week, and fix it (if feasible)...

**Comment by JohnAAbbott** [comment]
This should be (mostly) fixed by PR #44 -- thanks for finding the problem!

**Comment by alex-ozdemir** [comment]
Hi John,

Thank you for putting that patch together so quickly. That patch **does** allow the CoCoALib build to configure with compiler flag `"-fsanitize=address"`, which is an improvement. But, that patch doesn't solve the whole problem. It **does not** fix CoCoALib's implementation so that it actually passes the sanitizer when CoCoA is used at runtime.

To illustrate the remaining issue, consider this experiment, which still results in a failure:

```shell
$ git clone git@github.com:JohnAAbbott/CoCoALib.git -b JAA/CORRECT-gmp-check-cxxflags
$ cd CoCoALib
$ ./configure --only-cocoalib --with-cxxflags="-fsanitize=address"
[NOW THIS SUCCEEDS]
$ make -j $(nproc)
[BUILD SUCCEEDS, BUT ALL TESTS FAIL]
$ ./src/tests/test-empty
[FAILS WITH ASAN ERROR]
```

If it's relevant, my machine has GMP v6.3.0 (static) and g++ v15.1.1.

Cheers,
Alex

**Comment by JohnAAbbott** [comment]
My mistake: you need **also** PR #45  I believe that should resolve the problem.  I hope Anna will soon merge these PRs

**Comment by JohnAAbbott** [comment]
`clang` seems to work on my Arch Linux box (but no longer on my Ubuntu box -- the upgrade to 24.04 has been a major disappointment).  Anna had problems on her MacBook too.  I hope to investigate the issue at some point.
